ALTER TABLE `cctv`.`cctvs`
CHANGE COLUMN `tileName` `cctvName` VARCHAR(32) NOT NULL COMMENT '' ,
ADD COLUMN `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '' AFTER `source`,
ADD COLUMN `modifiedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '' AFTER `createdAt`,
ADD UNIQUE INDEX `cctvName_UNIQUE` (`cctvName` ASC)  COMMENT '';


ALTER TABLE `cctv`.`comments`
ADD COLUMN `modifiedAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '' AFTER `createdAt`;

