CREATE TABLE `cctv`.`users` (
  `userId` BIGINT NOT NULL AUTO_INCREMENT COMMENT '',
  `loginId` VARCHAR(256) NOT NULL COMMENT '',
  `token` VARCHAR(512) NOT NULL COMMENT '',
  `type` VARCHAR(128) NOT NULL COMMENT '',
  PRIMARY KEY (`userId`)  COMMENT '')
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;
